### ISSUE TITLE
is it available to use on Windows?

### ISSUE THREAD

**Issue by genvmoroz** [intel/powertelemetry#4]
is it available to use on Windows?

**Comment by p-zak** [comment]
Hello @genvmoroz
The library is designed for use in applications running only on Linux.

**Comment by genvmoroz** [comment]
> Hello @genvmoroz The library is designed for use in applications running only on Linux.

Are there similar repos here for Windows? Thanks.

**Comment by p-zak** [comment]
Unfortunately, rather not.
